# Generated by Django 2.1.5 on 2019-03-14 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0072_auto_20190312_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDetal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lk.UserDetal')),
            ],
        ),
    ]
