# Generated by Django 2.1.5 on 2019-03-14 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0073_uploaddetal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddetal',
            name='detal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lk.UserDetal', unique=True),
        ),
    ]
