# Generated by Django 2.1.5 on 2019-03-14 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0074_auto_20190314_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddetal',
            name='detal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lk.UserDetal'),
        ),
    ]
