# Generated by Django 2.1.5 on 2019-03-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0076_company_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='uploaded',
        ),
        migrations.AddField(
            model_name='userdetal',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
